import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/components/navbar";
import { SessionProvider } from "next-auth/react";
import Providers from "@/app/providers/Providers";
import ThemeBackground from "@/app/components/ThemeBackground";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceMono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space-mono',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={spaceMono.variable}>
        <Providers>
          <div>
            <ThemeBackground />
            <Navbar />
            <main className="relative">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
